name: Build for Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: sudo apt install libgl-dev xorg-dev gcc libc6-dev libx11-dev libxtst-dev libpng++-dev xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev xsel xclip

      - name: Build
        run: make

      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: quick-kill-linux
          path: quick-kill
